package main

import (
	"Sudoku/stagui"
	"image/color"
)

var buttonColor = color.RGBA{64, 64, 64, 255}

func (g *Game) initUI() {
	g.page = &stagui.Page{
		Title:   "",
		BgColor: color.Black,
		BgDraw:  true,
		Buttons: []*stagui.Button{
			{
				X:         60,
				Y:         1,
				W:         14,
				H:         7,
				Name:      "reset",
				BgColor:   buttonColor,
				Text:      "reset",
				TextColor: color.White,
				FontSize:  3,
			},
			{
				X:         75,
				Y:         1,
				W:         14,
				H:         7,
				Name:      "auto",
				BgColor:   buttonColor,
				Text:      "auto",
				TextColor: color.White,
				FontSize:  3,
			},
			{
				X:         55,
				Y:         15,
				W:         7,
				H:         7,
				Name:      "1",
				BgColor:   buttonColor,
				Text:      "1",
				TextColor: color.White,
				FontSize:  3,
			},
			{
				X:         63,
				Y:         15,
				W:         7,
				H:         7,
				Name:      "2",
				BgColor:   buttonColor,
				Text:      "2",
				TextColor: color.White,
				FontSize:  3,
			},
			{
				X:         71,
				Y:         15,
				W:         7,
				H:         7,
				Name:      "3",
				BgColor:   buttonColor,
				Text:      "3",
				TextColor: color.White,
				FontSize:  3,
			},
			{
				X:         55,
				Y:         23,
				W:         7,
				H:         7,
				Name:      "4",
				BgColor:   buttonColor,
				Text:      "4",
				TextColor: color.White,
				FontSize:  3,
			},
			{
				X:         63,
				Y:         23,
				W:         7,
				H:         7,
				Name:      "5",
				BgColor:   buttonColor,
				Text:      "5",
				TextColor: color.White,
				FontSize:  3,
			},
			{
				X:         71,
				Y:         23,
				W:         7,
				H:         7,
				Name:      "6",
				BgColor:   buttonColor,
				Text:      "6",
				TextColor: color.White,
				FontSize:  3,
			},
			{
				X:         55,
				Y:         31,
				W:         7,
				H:         7,
				Name:      "7",
				BgColor:   buttonColor,
				Text:      "7",
				TextColor: color.White,
				FontSize:  3,
			},
			{
				X:         63,
				Y:         31,
				W:         7,
				H:         7,
				Name:      "8",
				BgColor:   buttonColor,
				Text:      "8",
				TextColor: color.White,
				FontSize:  3,
			},
			{
				X:         71,
				Y:         31,
				W:         7,
				H:         7,
				Name:      "9",
				BgColor:   buttonColor,
				Text:      "9",
				TextColor: color.White,
				FontSize:  3,
			},
			{
				X:         63,
				Y:         39,
				W:         7,
				H:         7,
				Name:      "0",
				BgColor:   buttonColor,
				Text:      "0",
				TextColor: color.White,
				FontSize:  3,
			},
		},
		Text: []*stagui.StaticText{
			{
				Text:  "CurCode: 0",
				X:     60,
				Y:     9,
				Color: color.White,
				Font:  g.vis.GetFont("default"),
				Size:  3,
			},
		},
	}
}
